### ISSUE TITLE
PDI 8 crashing with SpoonGit

### ISSUE THREAD

**Issue by mkubacki** [HiromuHota/pdi-git-plugin#14]
**Environment:** Mac Os X 10.13.2, Java 9.0.4 build 11, PDI 8 downloaded this week, SpoonGit 1.0.0 master.

**Steps to reproduce:**

1. Open PDI8 vanilla install without any repo configured.
2. Don't configure repo, click Perspectives -> Git.
3. Select NO when asked to configure repo, no repo available.
4. PDI 8 crashes, disappearing from your screen.

**Comment by HiromuHota** [comment]
In a nutshell, Java 9 is not supported by PDI itself and hence not by SpoonGit either. See [here](https://help.pentaho.com/Documentation/8.0/Setup/Components_Reference) for system requirements.
Thanks for reporting (I haven't tested it myself before), but please use the supported version of Java (Oracle Java 8).

I tried to reproduce the issue under Mac OS X: 10.12.6, Oracle Java JDK: 9.0.4, PDI: 8.0.0.0-28, SpoonGit: 1.0.0, but I couldn't even launch Spoon.
At the very beginning of the log in the console, it complains about KettleURLClassLoader

```
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Listening for transport dt_socket at address: 5005
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.pentaho.di.core.plugins.KettleURLClassLoader (file:/Users/hiromu/Applications/pentaho/8.0.0.0/data-integration/launcher/../lib/kettle-core-8.0.0.0-28.jar) to field java.net.URLClassLoader.ucp
WARNING: Please consider reporting this to the maintainers of org.pentaho.di.core.plugins.KettleURLClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:32:56,625 INFO  [KarafBoot] Checking to see if org.pentaho.clean.karaf.cache is enabled
```

and lots of errors in Karaf thereafter like below.

```
ERROR: Bundle org.ops4j.pax.url.mvn [1] Error starting mvn:org.ops4j.pax.url/pax-url-aether/2.3.0 (org.osgi.framework.BundleException: Unresolved constraint in bundle org.ops4j.pax.url.mvn [1]: Unable to resolve 1.0: missing requirement [1.0] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.6.0)(!(version>=2.0.0))))
org.osgi.framework.BundleException: Unresolved constraint in bundle org.ops4j.pax.url.mvn [1]: Unable to resolve 1.0: missing requirement [1.0] osgi.wiring.package; (&(osgi.wiring.package=org.slf4j)(version>=1.6.0)(!(version>=2.0.0)))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by HiromuHota** [comment]
Turns out that an unpublished plugin was blocking Spoon to launch.
(Vanilla) Spoon can launch with Java 9, but still lacking the OSGi plugins.

I cleared the list of repositories and tried again, but couldn't reproduce the issue.
Since Java 9 is not supported by PDI and PDI might be changing on the way when it adapts to Java 9, I'll not pursue this issue any further at least for now.
