### ISSUE TITLE
Rephrase „Dirty working-tree“ message

### ISSUE THREAD

**Issue by diethardsteiner** [HiromuHota/pdi-git-plugin#21]
As a developer I found the „Dirty working-tree“ error message a bit confusing when clicking on the Pull button. The error message seems to show because there are uncommitted changes in the working tree. Can you please change the error message to something like: "Cannot pull because there are uncommitted changes in the working tree." Thanks!

**Comment by HiromuHota** [comment]
Thank you for pointing this out!
Resolved by b393033e3d664f1217b1eba197d3d5e9235055e6.

**Comment by diethardsteiner** [comment]
Thanks a lot!
