### ISSUE TITLE
Make the repository settings dialog resizable

### ISSUE THREAD

**Issue by mattcasters** [HiromuHota/pdi-git-plugin#24]
EditRepositoryDialog.java

**Comment by HiromuHota** [comment]
The following minimum change makes the dialog resizable.

```
   public EditRepositoryDialog( Shell parentShell, GitRepository repo ) {
     super( parentShell );
+    setShellStyle( SWT.DIALOG_TRIM | SWT.RESIZE );
     this.repo = repo;
   }
```

**Comment by HiromuHota** [comment]
https://github.com/HiromuHota/pdi-git-plugin/pull/25#issuecomment-447635844
> it's not just having the ability to resize, it's also remembering the last size.
