### ISSUE TITLE
Can't get this to work with Enterprise Git Account

### ISSUE THREAD

**Issue by kent5440** [HiromuHota/pdi-git-plugin#33]
Hi,

I tried within WebSpoon and then in a regular PDI CE 7.1 download but both throw the same error so I am thinking perhaps it doesn't work with Enterprise GitHub Accounts?

Steps
1) change to git perspective
2) clone
3) enter in details for the clone edit fields 
    source url -> "https://github.<enterprise-customer>.com/<repo-name>"   *** will not show the actual URL  in the issues for some reason ***
    type -> git
    directory -> /git-test
    etc etc

When you hit enter you get this pop up error message:

"git-upload-pack not permitted on https://github.<enterprise-customer>.com/<repo-name>"

Thoughts?

Thanks!

**Comment by HiromuHota** [comment]
Hi,

Is this Enterprise GitHub a self-hosted with self-signed SSL certificate?

Try `git config http.sslVerify false` on PDI CE 7.1.
(See here: https://stackoverflow.com/a/9841665 for details).

**Comment by HiromuHota** [comment]
Close for inactivity. Feel free to reopen it if an issue persists.
