### ISSUE TITLE
Support regarding this plugin for Pentaho

### ISSUE THREAD

**Issue by theeagle-code** [HiromuHota/pdi-git-plugin#43]
Dear HiromuHota,

Great work on creating this plugin. Started installing recently and will continue testing for implementation finally.

I was wondering how things are related to long-term support from a development perspective and supplier perspective? Is there any guarantee or agreement how this will go down in the future?

Will Pentaho or Hitachi support this officially?

**Comment by HiromuHota** [comment]
@theeagle-code thanks for your interests.
This project is not supported by Hitachi Vantara.
As a maintainer, I'll maintain this project as much as possible but cannot guarantee anything.

If you are interested, this project has been ported to the Project Hop (now Apache Hop).
https://www.project-hop.org/
