### ISSUE TITLE
prevent commit of security related information

### ISSUE THREAD

**Issue by RutgerDOW** [HiromuHota/pdi-git-plugin#8]
Hello Hiromu, I spoke to you at PCM17, about your great git implementation in pdi.

Here is the information of Jens i mentioned:
[pdikettle-solution-share](http://kettle.bleuel.com/2015/02/05/pdikettle-solution-share-presented-at-pcmd15/)

We self use a 2 convenience script before commit:
checks for passwords en keys in ktr/kjb: 
*every value string starting with "Encrypted "
*every xml tag with "password"  (case insensitive)
*every xml tag with "private"  (case insensitive) and CDATA in value  

clear all (shared) connection data from ktr/kjb   (just to keep files small, the informatie is automatically added by pdi when opening/using file with info from shared.xml)

Maybe this can be done by git hooks in your project? Or by some user configuration with predefined options what not to include/exclude in file before commit

**Comment by HiromuHota** [comment]
Hi Rutger,

Thanks for your great feedbacks!

I think you can trigger those scripts by git hooks.
According to [Bug 493721](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493721), "Currently (as of 2016-05-16) JGit supports the following hooks on Posix and cygwin : pre-commit, commit-msg, pre-push"
Please try and tell me how it goes.
And also please share the scripts if possible for the benefit of others.

**Comment by HiromuHota** [comment]
I tried pre-commit hook and confirmed that pre-commit is hooked by commit.
![screen shot 2017-11-22 at 4 26 55 pm](https://user-images.githubusercontent.com/20668349/33155088-22c1ef6c-cfa2-11e7-99bb-f670cfd2ec22.png)
